### ISSUE TITLE
Automating the setup for running the webapp in docker

### ISSUE THREAD

**Issue by AI-Pree** [fisher60/Friendo_Site_Django#26]
I don't wanna type that docker compose command everytime and install docker manually everytime when I'm testing it new env or system. So I'm writing a install.sh file to automate the whole process for setting up the environment to run this project in dev mode.

**Comment by fisher60** [comment]
That sounds like a good idea. We should have the ability to `up` the container as well as `up --build` the container with simple scripts, perhaps?

**Comment by AI-Pree** [comment]
Ye I was gonna add up everything. I will post the list of things it does after I'm done. Thank you
